global:
  smtp_smarthost: 'smtpd:25'
  smtp_from: 'alertmanager@stevenc4.com'
  smtp_require_tls: false

route:
    group_by: ['alertname', 'hostname']
    group_interval: 2m
    group_wait: 30s
    receiver: 'email'
    repeat_interval: 2h

templates:
  - '/etc/alertmanager/email.tmpl'

receivers:
  - name: 'email'
    email_configs:
    - to: 'stevencarroll90@gmail.com'
      from: 'alertmanager@stevenc4.com'
      smarthost: 'smtpd:25'
      headers:
        Subject: '{{ template "email.subject" . }}'
      text: '{{ template "email.text" . }}'
