global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@stevenc4.com'

route:
    receiver: 'email'

receivers:
    - name: 'email'
      email_configs:
      - to: 'stevencarroll90@gmail.com'
