services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    environment:
      - PIHOLE_PROTOCOL=http
      - PIHOLE_HOSTNAME=192.168.201.10
      - PIHOLE_PORT=8080
    env_file:
      - ./env/pihole-exporter.env
    network_mode: host
    restart: unless-stopped
