networks:
  smtp-net:
    external: true

volumes:
  grafana_data: {}

services:
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - "--web.external-url=https://alertmanager.local"
    restart: unless-stopped
    ports:
      - "9093:9093"
    expose:
      - 9093
    networks:
      - home-reverse-proxy-net
      - monitor-net
      - smtp-net
    labels:
      - monitor_group=monitoring
      - homepage.group=Util
      - homepage.name=Alert Manager
      - homepage.icon=alertmanager
      - homepage.href=https://alertmanager.carroll.live
      - homepage.description=Alert Manager client
      - traefik.enable=true
      - traefik.docker.network=home-reverse-proxy-net
      - traefik.http.routers.alertmanager.rule=Host(`alertmanager.carroll.live`) || Host(`alertmanager.stevenc4.com`)
      - traefik.http.routers.alertmanager.entrypoints=websecure
      - traefik.http.routers.alertmanager.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=steven:$$2y$$05$$1ZYT5NkVLiQETZI6b86MSOn8TfOrKmkvMZgmf7Rmx2Q2YNsxXOU9a
      - traefik.http.routers.alertmanager.tls.certresolver=carroll_live_dns_resolver
      - traefik.http.services.alertmanager.loadbalancer.server.port=9093
      - coredns.enabled=true
      - coredns.a.1.name=alertmanager.carroll.live
      - coredns.a.2.name=alertmanager.stevenc4.com

  cadvisor:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256m"

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    env_file:
      - ./env/grafana.env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3001:3000"
    networks:
      - monitor-net
      - home-reverse-proxy-net
    labels:
      - monitor_group=monitoring
      - homepage.group=Util
      - homepage.name=Grafana
      - homepage.icon=grafana
      - homepage.href=https://grafana.carroll.live
      - homepage.description=Grafana client
      - traefik.enable=true
      - traefik.docker.network=home-reverse-proxy-net
      - traefik.http.routers.grafana.rule=Host(`grafana.carroll.live`) || Host(`grafana.stevenc4.com`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=carroll_live_dns_resolver
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - coredns.enabled=true
      - coredns.a.1.name=grafana.carroll.live
      - coredns.a.2.name=grafana.stevenc4.com

  ofelia-dockprom:
    container_name: ofelia-dockprom
    image: mcuadros/ofelia:latest
    command: daemon --config=/opt/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/mozart:/opt
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.6.0
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - monitor-net
    labels:
      monitor_group: monitoring

  zfs-utils:
    container_name: zfs-utils
    build:
      context: ./zfs-utils
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /dev:/dev:ro
      - ./textfile_collector:/zfs-metrics
    labels:
      - com.centurylinklabs.watchtower.enable=false
