global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: mozart

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host: 192.168.205.10
          hostname: mozart

  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          host: 192.168.205.10
          hostname: mozart

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          host: 192.168.205.10
          hostname: mozart

  - job_name: 'watchtower'
    scrape_interval: 15s
    metrics_path: /v1/metrics
    bearer_token_file: /run/secrets/watchtower_bearer_token
    static_configs:
      - targets: ['watchtower:8080']
        labels:
          host: 192.168.205.10
          hostname: mozart

  - job_name: 'pushgateway'
    scrape_interval: 15s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'satellites'
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: [job]
        target_label: original_job
      - source_labels: [exported_job]
        target_label: job
    static_configs:
      - targets:
          - 192.168.201.10:9090 # pi.hole
        labels:
          source: satellite
          host: 192.168.201.10
          hostname: dns1
      - targets:
          - 192.168.201.11:9090 # pi.hole
        labels:
          source: satellite
          host: 192.168.201.11
          hostname: dns2
      - targets:
          - 192.168.201.12:9090 # pi.hole
        labels:
          source: satellite
          host: 192.168.201.12
          hostname: dns2
      - targets:
          - 192.168.201.20:9090 # wireguard1
        labels:
          source: satellite
          host: 192.168.201.20
          hostname: wireguard1
  
  - job_name: 'satellite-federation'
    scrape_interval: 15s
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~".*"}'
    metric_relabel_configs:
      - source_labels: [job]
        target_label: original_job
      - source_labels: [exported_job]
        target_label: job
    static_configs:
      - targets:
          - '192.168.201.10:9090'  # pi.hole
          - '192.168.201.11:9090'  # wireguard1
        labels:
          source: satellite