global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: pihole

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host: 192.168.201.10
          hostname: pihole

  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          host: 192.168.201.10
          hostname: pihole

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          host: 192.168.201.10
          hostname: pihole

  - job_name: 'watchtower'
    scrape_interval: 15s
    metrics_path: /v1/metrics
    bearer_token_file: /run/secrets/watchtower_bearer_token
    static_configs:
      - targets: ['watchtower:8080']
        labels:
          host: 192.168.201.10
          hostname: pihole

  - job_name: 'pihole'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['pihole-exporter:9617']
  